name: custom_form_w
description: "Custom Form Widget With Validation Button and more features "
version: 2.0.7
license: MIT
homepage: "https://github.com/wogoodwael/custom_form_w.git"
Author: "Wogood wael "
# publish_to: 'https://pub.dev'
screenshots:
  - description: 'CustomFormW Example 1'
    path: "screenshots/image_one.png"
  - description: 'CustomFormW Example 2'
    path: "screenshots/image_two.png"
  - description: 'CustomFormW Example 3'
    path: "screenshots/image_three.png"
  - description: 'CustomFormW Example 4'
    path: "screenshots/image_four.png"
  - description: 'CustomFormW Example 5'
    path: "screenshots/image_five.png"
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
